repositories:
  - name: prometheus-grafana
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: loki
    namespace: lgtm
    createNamespace: true
    chart: grafana/loki-distributed
    values:
      - ./loki/values-loki.yaml

  - name: prometheus-stack
    namespace: lgtm
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    values:
      - ./prometheus/values-prometheus.yaml

  - name: promtail
    namespace: lgtm
    createNamespace: true
    chart: grafana/promtail
    values:
      - ./promtail/values-promtail.yaml

  - name: tempo
    namespace: lgtm
    createNamespace: true
    chart: grafana/tempo-distributed
    values:
      - ./tempo/values-tempo.yaml