receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: $URL_TEMPO

  prometheus:                   
    endpoint: "0.0.0.0:9090" 

processors:
  batch:
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [otlp] 
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]